import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/schema/workspace.ts',
    'src/schema/agent.ts',
    'src/schema/trigger.ts',
    'src/schema/flow.ts',
    'src/schema/plugin.ts',
    'src/schema/vault.ts',
    'src/schema/memory.ts',
    'src/schema/observability.ts',
    'src/schema/security.ts',
    'src/schema/cloud.ts',
    'src/events/event.ts',
    'src/auth/principal.ts',
    'src/auth/capability.ts',
    'src/errors/codes.ts',
    'src/errors/error.ts',
    'src/schema/config-root.ts',
    'src/config/merge.ts',
    'src/config/migrate.ts',
    'src/config/diff.ts',
    'src/auth/verify.ts',
    'src/secrets/refs.ts',
    'src/secrets/providers.ts',
    'src/events/bus.ts',
    'src/schema/rag.ts',
    'src/schema/agent-registry.ts',
    'src/schema/agent-version.ts',
    'src/schema/eval.ts',
    'src/runtime/run-mode.ts',
    'src/security/egress.ts',
    'src/tools/side-effects.ts',
    'src/tools/sandbox.ts',
    'src/audit/batch.ts',
    'src/plugins/catalog.ts',
    'src/lockfile/lock.ts',
    'src/brand/brand-kit.ts',
    'src/consent/consent.ts',
    'src/obs/gen-ai-semconv.ts',
    'src/cost/cost-meter.ts',
    'src/security/airgap.ts',
    'src/runtime/adapter-fallback.ts',
    'src/runtime/workspace-paths.ts',
    'src/runtime/agent-lifecycle.ts',
    'src/runtime/agent-registry-store.ts',
    'src/obs/telemetry.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: true,
  target: 'es2022',
  external: ['zod'],
})
